language: cpp
compiler: gcc
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libarmadillo-dev
    - libarmadillo2
script:
- make test
after_success:
- "./tiresias_tests"
notifications:
  email:
    on_success: change
    on_failure: change
branches:
  only: master
os: linux
