language: cpp

compiler: gcc

sudo: required

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y libarmadillo2
- sudo apt-get install -y libarmadillo-dev

script: make

branches:
  only: master

os: linux
