box: njanetos/tiresias-docker
build:
    steps:
        - script:
            name: build
            code: |
                echo `ls`
                cd tiresias
                make all
                ./tiresias_tests

