# Specify the target file and the install directory
SRC = src
INC = include
LIB = lib

CLEANEXTS               = o a gcno
CC			= g++-6
CFLAGS			= -Wall -fexceptions -g -I$(INC) -I/usr/local/include -std=c++11 -fPIC
CFLAGS_BUILD		= -Wall -fexceptions -g -I$(INC) -I/usr/local/include -fPIC
LIBS			= -L$(LIB) -L/usr/local/lib -larmadillo -lMvtnorm -lnlopt

_DEPS = mvtnorm.h libtiresias.h c_rand_var_norm.h c_logger.h catch.hpp common.h
DEPS = $(patsubst %,$(INC)/%,$(_DEPS))

_OBJ = libtiresias.o c_rand_var_norm.o c_logger.o c_tests.o
OBJ = $(patsubst %,%,$(_OBJ))

# Default target
.PHONY: all
all: tiresias_tests

tiresias_tests: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS) $(LIBS)

# Dependencies

%.o: $(SRC)/%.cpp $(DEPS)
	$(CC) $(CFLAGS) -c -o $@ $<
